[package]
name = "varaibles"
version = "2.3.4"
edition = "2021"
authors = ["Anaga <bobyrev.bob@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
